### ISSUE TITLE
License for your project

### ISSUE THREAD

**Issue by rafee** [Orodan/personal-website#6]
Hi, I forked your project to create my portfolio website. However, I just realized there's no License on your page. Are you ok with me using your content (with my details)? If yes, could you please add a license to your project?

**Comment by Orodan** [comment]
Hi @rafee, feel free to create your portfolio from what I did. As long as you don't copy my own content (experience details, articles, etc) I don't mind. Also I think the more you do your portfolio by yourself, the most value it will have :)

It's a good idea to add a license but I must say I don't really know what kind of license could fit my project, any recommandation ?

**Comment by rafee** [comment]
I like to have something to look at all times. If I start entirely from scratch, it would be a long time before I get something to see. Add to that the fact that, I am quite weak at front-end (more of a backend guy). I spent my energy on learning to deploy and extend it using AWS and more specifically Amplify (From my POV that seemed like a more worthy investment).

If you are asking for suggestion on license, MIT License is quite flexible, I use that for most of my works.

This can be a useful [link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository).

**Comment by rafee** [comment]
Also, as for your article, right now it's part of my [url](https://rafee.me/), but I'll remove them soon. I am finishing page by page. I think I will have the whole thing sorted out by this weekend. Also, I plan to author an article extending your one, i.e. how to deploy this on AWS Amplify and how to add authentication to it.

**Comment by Orodan** [comment]
I'll take a look to the MIT license thanks

As I said you can fork the project and use it to build your own portfolio, as long as you use your own story and not mine ^^ 

Also thanks for taking the time to ask, I hope you learned a bit by using this project and I look forward to your article on AWS Amplify and authentication 😄
